services:
  vsgkugelberg-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: vsgkugelberg-frontend
    restart: unless-stopped
    networks:
      - web
    environment:
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - web

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - web

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - web

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${GRAFANA_SUBDOMAIN}
      - LETSENCRYPT_HOST=${GRAFANA_SUBDOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    ports:
      - "3000:3000"
    networks:
      - web

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    restart: unless-stopped
    command: --nginx.scrape-uri https://vsgkugelberg-frontend/nginx_status
    ports:
      - "9113:9113"
    networks:
      - web

networks:
  web:
    name: web

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
